import { COLORS } from "@/app/constants";
import { StyleSheet } from "react-native";

export const poiFilterStyles = StyleSheet.create({
  filterChip: {
    backgroundColor: COLORS.bgDark,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    zIndex: 60,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  backdrop: {
    // was generated by copilot, seems to work for now
    position: "absolute",
    top: -1000,
    left: -1000,
    width: 3000,
    height: 3000,
    zIndex: 40,
  },
  dropdownOptionsContainer: {
    position: "absolute",
    top: 44,
    left: 0,
    right: 0,
    backgroundColor: COLORS.bgDark,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    overflow: "hidden",
    zIndex: 50,
  },
});
