import { COLORS } from "@/app/constants";
import { StyleSheet } from "react-native";

export const poiFilterStyles = StyleSheet.create({
  filterScrollView: {
    display: "flex",
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 10,
    minHeight: 52,
    paddingVertical: 4,
    overflow: "visible",
  },
  filterChip: {
    backgroundColor: COLORS.bgDark,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    zIndex: 60,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  backdrop: {
    // was generated by copilot, seems to work for now
    position: "absolute",
    top: -1000,
    left: -1000,
    width: 3000,
    height: 3000,
    zIndex: 40,
  },
  dropdownOptionsContainer: {
    position: "absolute",
    top: 44,
    left: 0,
    right: 0,
    backgroundColor: COLORS.bgDark,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    overflow: "hidden",
    zIndex: 1000,
    elevation: 1000,
  },
});

export const poiMiscStyles = StyleSheet.create({
  updateButton: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: COLORS.selectionBlue,
    borderRadius: 8,
  },
});

export const poiMarkerStyles = StyleSheet.create({
  marker: {
    backgroundColor: COLORS.poiMarkerBlue,
    padding: 4,
    borderRadius: 32,
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.background,
  },
});

export const poiListStyles = StyleSheet.create({
  itemContainer: {
    paddingTop: 8,
    paddingBottom: 16,
    display: "flex",
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomColor: COLORS.border,
    borderBottomWidth: 1,
  },
});
