/**
 * Simplifies the address down to the civic number and street name.
 * @param address the original address as returned by Google Maps/the POI endpoint
 * @returns the simplified address
 */
export function getSimplifiedAddress(address: string) {
  const parts = address.split(",");
  return parts.slice(0, -3).join(",").trim();
}

/**
 * Takes a distance value in meters and simply formats it as a string, in meters if less than 1000m, and in kilometers otherwise
 * @param distanceInMeters
 * @returns the distance formatted as a string, in meters if less than 1000m, and in kilometers otherwise
 */
export function getDistanceDisplayText(distanceInMeters: number): string {
  if (distanceInMeters < 1000) {
    return `${distanceInMeters.toFixed(0)} m`;
  } else {
    return `${(distanceInMeters / 1000).toFixed(1)} km`;
  }
}

// used in stripHTMLTags
const parseTagMeta = (tag: string) => {
  let index = 1;

  while (index < tag.length && (tag[index] === " " || tag[index] === "\t" || tag[index] === "\n" || tag[index] === "\r")) {
    index++;
  }

  const isClosing = tag[index] === "/";
  if (isClosing) {
    index++;
  }

  while (index < tag.length && (tag[index] === " " || tag[index] === "\t" || tag[index] === "\n" || tag[index] === "\r")) {
    index++;
  }

  const start = index;
  while (
    index < tag.length &&
    tag[index] !== " " &&
    tag[index] !== "\t" &&
    tag[index] !== "\n" &&
    tag[index] !== "\r" &&
    tag[index] !== "/" &&
    tag[index] !== ">"
  ) {
    index++;
  }

  return {
    isClosing,
    name: tag.slice(start, index).toLowerCase(),
  };
};

// used in stripHTMLTags
const decodeHtmlEntities = (text: string) => {
  const entityMap: Record<string, string> = {
    "&nbsp;": " ",
    "&amp;": "&",
    "&quot;": '"',
    "&#39;": "'",
    "&lt;": "<",
    "&gt;": ">",
  };

  let result = "";
  let index = 0;

  while (index < text.length) {
    if (text[index] !== "&") {
      result += text[index];
      index++;
      continue;
    }

    const semicolonIndex = text.indexOf(";", index + 1);
    if (semicolonIndex === -1) {
      result += text[index];
      index++;
      continue;
    }

    const entity = text.slice(index, semicolonIndex + 1);
    const replacement = entityMap[entity.toLowerCase()];

    if (replacement === undefined) {
      result += text[index];
      index++;
      continue;
    }

    result += replacement;
    index = semicolonIndex + 1;
  }

  return result;
};

// used in stripHTMLTags
const normalizeWhitespace = (text: string) => {
  const output: string[] = [];

  const lastChar = () => output.at(-1);

  const popTrailingSpace = () => {
    if (lastChar() === " ") {
      output.pop();
    }
  };

  const isSpaceChar = (char: string) =>
    char === " " || char === "\t" || char === "\f" || char === "\v";

  const appendNewline = () => {
    popTrailingSpace();
    if (output.length > 0 && lastChar() !== "\n") {
      output.push("\n");
    }
  };

  for (let index = 0; index < text.length; index++) {
    let char = text[index];

    if (char === "\r") {
      if (text[index + 1] === "\n") {
        index++;
      }
      char = "\n";
    }

    if (char === "\n") {
      appendNewline();
      continue;
    }

    if (isSpaceChar(char)) {
      const previousChar = lastChar();
      if (output.length === 0 || previousChar === "\n" || previousChar === " ") {
        continue;
      }

      output.push(" ");
      continue;
    }

    output.push(char);
  }

  return output.join("").trim();
};


/**
 * 
 * Strips HTML tags from the given text, decodes HTML entities, and normalizes whitespace. 
 * Also adds newlines for <div> tags since those are used in the instructions to separate different steps.
 * The entire chain of functions is generated by GitHub Copilot.
 * 
 * Used in the directions screen to display the instructions returned by the Google Directions API in a readable format.
 * 
 * @param text html instruction text from Google Directions API (returned by the directions endpoint)
 * @returns the instruction text with HTML tags stripped, HTML entities decoded, and whitespace normalized
 */
export const stripHtmlTags = (text: string) => {
  let output = "";
  let insideTag = false;
  let tagBuffer = "";

  for (const char of text) {
    if (!insideTag) {
      if (char === "<") {
        insideTag = true;
        tagBuffer = "<";
      } else {
        output += char;
      }

      continue;
    }

    tagBuffer += char;

    if (char !== ">") {
      continue;
    }

    const { isClosing, name } = parseTagMeta(tagBuffer);
    if (!isClosing && name === "div") {
      output += "\n";
    }

    insideTag = false;
    tagBuffer = "";
  }

  if (insideTag) {
    output += tagBuffer;
  }

  return normalizeWhitespace(decodeHtmlEntities(output));
};
